spring:
  profiles:
    active: dev
  application:
    name: oa-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
  data:
    redis:
      password: 123321
      host: 192.168.0.88
logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl